"""IR-B1-03: native V1 Store retention versus real temporary Recorder eligibility."""

import asyncio
import datetime as dt
import hashlib
import json
import os
from pathlib import Path
from unittest.mock import AsyncMock

import pytest
from homeassistant.core import HomeAssistant
from homeassistant.helpers.storage import Store
from homeassistant.util import dt as dt_util

from custom_components.csg_plus.energy_statistics import (
    EnergyStatisticsBridge, build_statistics, statistic_metadata,
)
from custom_components.csg_plus.history_store import CSGHistoryStore
from test_energy_statistics_recorder import ACCOUNT, SHANGHAI, recorder_world

FIXTURE = Path(__file__).parent / "fixtures/beta1-retained-future.json"
KEY = "csg_plus.history_store.synthetic-energy-entry"


def file_state(path):
    return {"sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
            "mtime_ns": path.stat().st_mtime_ns}


def observed(name, data):
    if directory := os.environ.get("CSG_RESIDUAL_EVIDENCE_DIR"):
        output = Path(directory)
        output.mkdir(parents=True, exist_ok=True)
        (output / f"{name}.json").write_text(
            json.dumps(data, indent=2, default=str) + "\n", encoding="utf-8",
        )


async def seed_legacy(tmp_path, *, future_only=False):
    """Business payload generated by fixed beta.1 Store; native HA V1 wrapper."""
    payload = json.loads(FIXTURE.read_text(encoding="utf-8"))
    if future_only:
        payload["accounts"][ACCOUNT]["daily_usage"] = {
            "2026-09-30": payload["accounts"][ACCOUNT]["daily_usage"]["2026-09-30"],
        }
    hass = HomeAssistant(str(tmp_path))
    try:
        await Store(hass, 1, KEY).async_save(payload)
    finally:
        await hass.async_stop(force=True)
    return payload["accounts"][ACCOUNT]["daily_usage"], tmp_path / ".storage" / KEY


def row_values(rows):
    return [(dt.datetime.fromtimestamp(row["start"], dt.UTC).astimezone(SHANGHAI).date().isoformat(),
             row["state"], row["sum"]) for row in rows]


@pytest.mark.parametrize("advance_day", [30, 31], ids=["on-fact-date", "after-fact-date"])
def test_fresh_reload_and_date_advance_preserve_legacy_file(
    tmp_path, recorder_world, monkeypatch, caplog, advance_day,
):
    clock = [dt.datetime(2026, 9, 2, 16, tzinfo=dt.UTC)]  # Shanghai September 3
    monkeypatch.setattr(dt_util, "utcnow", lambda: clock[0])

    async def scenario():
        expected, path = await seed_legacy(tmp_path)
        before = file_state(path)
        async with recorder_world() as world:
            dt_util.set_default_time_zone(dt.UTC)  # HA default must not change business date
            assert await world.store.async_daily_usage_snapshot(ACCOUNT) == expected
            world.store._store.async_save = AsyncMock(side_effect=AssertionError("No Store rewrite"))
            await world.sync()
            fresh = await world.query()
            assert row_values(fresh) == [("2026-09-02", 2, 2), ("2026-09-03", 0, 2)]
            assert file_state(path) == before
            for _ in range(3):
                await world.sync()
            warnings = [r.getMessage() for r in caplog.records
                        if "future relative to Asia/Shanghai business day" in r.getMessage()]
            assert len(warnings) == 1
            assert not any(value in warnings[0] for value in (ACCOUNT, "2026-09-30", "9.0"))

            await world.bridge.async_shutdown()
            reloaded = CSGHistoryStore(world.hass, world.entry.entry_id)
            await reloaded.async_load()
            assert await reloaded.async_daily_usage_snapshot(ACCOUNT) == expected
            reloaded._store.async_save = AsyncMock(side_effect=AssertionError("No Store rewrite"))
            worker = EnergyStatisticsBridge(world.hass, world.entry, reloaded)
            try:
                await world.sync(worker)
                assert await world.query() == fresh
                assert file_state(path) == before
                clock[0] = (dt.datetime(2026, 9, 30, tzinfo=SHANGHAI)
                            + dt.timedelta(days=advance_day - 30)).astimezone(dt.UTC)
                await world.sync(worker)
                advanced = await world.query()
                assert row_values(advanced) == [
                    ("2026-09-02", 2, 2), ("2026-09-03", 0, 2), ("2026-09-30", 9, 11),
                ]
                assert advanced[:2] == fresh
                assert await reloaded.async_daily_usage_snapshot(ACCOUNT) == expected
                assert file_state(path) == before
                observed(f"retained-fresh-reload-advance-{advance_day}", {
                    "store_facts": expected, "file_before": before, "file_after": file_state(path),
                    "fresh_rows": fresh, "advanced_rows": advanced, "imports": world.imports,
                })
            finally:
                await worker.async_shutdown()
            world.store._store.async_save.assert_not_awaited()
            reloaded._store.async_save.assert_not_awaited()
    asyncio.run(scenario())


def test_existing_legal_recorder_history_is_preserved(tmp_path, recorder_world, monkeypatch):
    monkeypatch.setattr(dt_util, "utcnow", lambda: dt.datetime(2026, 9, 3, 4, tzinfo=dt.UTC))

    async def scenario():
        expected, path = await seed_legacy(tmp_path)
        before = file_state(path)
        async with recorder_world() as world:
            from homeassistant.components.recorder.statistics import async_add_external_statistics
            async_add_external_statistics(world.hass, statistic_metadata(ACCOUNT),
                                          build_statistics({"2026-09-02": expected["2026-09-02"]}))
            await world.drain()
            prior = await world.query()
            assert row_values(prior) == [("2026-09-02", 2, 2)]
            await world.sync()
            after = await world.query()
            assert row_values(after) == [("2026-09-02", 2, 2), ("2026-09-03", 0, 2)]
            assert after[:1] == prior
            assert len(world.imports) == 1
            assert [row["start"].date().isoformat() for row in world.imports[0][1]] == ["2026-09-03"]
            assert await world.store.async_daily_usage_snapshot(ACCOUNT) == expected
            assert file_state(path) == before
            observed("retained-existing-legal-history", {"prior": prior, "after": after,
                     "imports": world.imports, "file_before": before, "file_after": file_state(path)})
    asyncio.run(scenario())


def test_all_future_facts_stay_out_of_finalization(tmp_path, recorder_world, monkeypatch):
    monkeypatch.setattr(dt_util, "utcnow", lambda: dt.datetime(2026, 9, 3, 4, tzinfo=dt.UTC))

    async def scenario():
        expected, path = await seed_legacy(tmp_path, future_only=True)
        before = file_state(path)
        async with recorder_world() as world:
            await world.sync()
            assert await world.query() == []
            await world.bridge.async_shutdown()
            await world.drain()
            assert await world.query() == []
            assert world.imports == []
            assert await world.store.async_daily_usage_snapshot(ACCOUNT) == expected
            assert file_state(path) == before
            observed("retained-all-future-finalization", {"store_facts": expected, "imports": [],
                     "file_before": before, "file_after": file_state(path)})
    asyncio.run(scenario())
